ARG RUBY_VERSION=2.6.6
FROM ruby:${RUBY_VERSION}-slim-buster

ARG BUNDLER_VERSION=2.4.22

ENV APP_PATH=/app \
    BUNDLE_PATH=/box \
    RAILS_ENV=production \
    RACK_ENV=production \
    NODE_ENV=production \
    RAILS_LOG_TO_STDOUT=true \
    RAILS_SERVE_STATIC_FILES=true

RUN sed -i 's/deb.debian.org/archive.debian.org/g' /etc/apt/sources.list && \
    sed -i 's/security.debian.org/archive.debian.org/g' /etc/apt/sources.list

RUN apt-get update -qq && apt-get install -y --no-install-recommends \
    bash \
    build-essential \
    git \
    libpq-dev \
    postgresql-client \
    shared-mime-info \
    nodejs \
    npm \
    ca-certificates \
    curl \
    procps \
  && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN npm i -g yarn
RUN gem update --system 3.3.22 && gem install bundler -v ${BUNDLER_VERSION}

WORKDIR ${APP_PATH}

COPY Gemfile Gemfile.lock ./
RUN bundle config set without 'development test' && \
    bundle config set deployment 'true' && \
    bundle install --jobs 4 --retry 3

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

RUN chmod +x ./docker/entrypoint.prod.sh

EXPOSE 3000

CMD ["bash", "-lc", "bundle exec rails server -b 0.0.0.0 -p 3000"]
