development:
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE", "dev_dummy_secret_key_base") %>
  DEVISE_SECRET_KEY: <%= ENV.fetch("DEVISE_SECRET_KEY", "dev_dummy_devise_secret_key") %>
  REDIS_URL: <%= ENV.fetch("REDIS_URL", "redis://redis:6379/0") %>

test:
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE", "test_dummy_secret_key_base") %>
  DEVISE_SECRET_KEY: <%= ENV.fetch("DEVISE_SECRET_KEY", "test_dummy_devise_secret_key") %>
  REDIS_URL: <%= ENV.fetch("REDIS_URL", "redis://redis:6379/1") %>

production:
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE") %>
  DEVISE_SECRET_KEY: <%= ENV.fetch("DEVISE_SECRET_KEY") %>
  REDIS_URL: <%= ENV.fetch("REDIS_URL", "redis://redis:6379/0") %>
